name: deploy
on:
  push:
    branches:
      - main

env:
  APP_NAME: air-traffic-control

jobs:
  deploy:
    environment: production
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # fetch the go version from the .go-version file
      - name: fetch go version
        id: go-version
        run: |
          version=$(cat .go-version)
          echo "version=${version}" >> $GITHUB_OUTPUT

      - name: setup go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ steps.go-version.outputs.version }}

      - name: go build
        run: go build

      - name: deploy
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.APP_NAME }}
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: .
